### ISSUE TITLE
Open to supporting alternative executable name for `bat` in this module?

### ISSUE THREAD

**Issue by antoineco** [zimfw/fzf#5]
Like the title suggests, I wanted to gauge whether there was interest on your side to support an alternative executable name for `bat`, in order to help people adopt the module without having to perform extra set up on their end.

The specific use-case I have in mind comes from Debian and its derivatives, which create the `bat` executable as `batcat` (possibly to avoid a conflict with another package):
```console
% dpkg -L bat
/.
/usr
/usr/bin
/usr/bin/batcat
```

Right now it is possible to create a symlink manually in the PATH, or to fiddle with `$commands`, but given the popularity of Debian-like distros I think it could be convenient and relatively safe to fallback to `batcat` if `bat` doesn't exist.

**Comment by ericbn** [comment]
Hallo @antoineco. First thank you for the support you give to Zim users in our issues and discussions!

Sure, I was not aware of bat also being installed as batcat in some distros. Fair enough, we could fallback to trying batcat if bat is not found. I can work on this.

**Comment by antoineco** [comment]
Fantastic, thank you!

In case you're busy I can happily sent a PR, the change is trivial.

**Comment by ericbn** [comment]
@antoineco, cool, please go ahead.
