### ISSUE TITLE
Missing tab key binding to fzf-complete

### ISSUE THREAD

**Issue by fikovnik** [zimfw/fzf#7]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

Missing '^I' binding to `fzf-completion`.

# This should be up so other modules can access tools installed by homebrew
zmodule homebrew
zmodule archive
zmodule romkatv/powerlevel10k
zmodule fzf
zmodule fasd

### Steps to reproduce

1. ```
   cd ${$(mktemp -d):A} && \
       ZDOTDIR=${PWD} HOME=${PWD} ZIM_HOME=${PWD}/.zim && \
       curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh && \
       exec zsh
   ```
2. Enable `homebrew` and `fzf` module
(I use homebrew to install fzf - otherwise it is not needed)

### Current behavior

FZF bound keys are missing the tab bound to fzf-complete:

   ```
    % bindkey -M emacs | grep fzf
    "^R" fzf-history-widget
    "^T" fzf-file-widget
    "^[c" fzf-cd-widget
   ```

### Expected behavior

```
% bindkey -M emacs | grep fzf
"^I" fzf-completion
"^R" fzf-history-widget
"^T" fzf-file-widget
"^[c" fzf-cd-widget
```

which is the behavior after `source <(fzf --zsh)`

### zimfw info

```shell
zimfw version:        1.14.0 (built at 2024-06-25 17:29:35 UTC, previous commit is 3b7908d)
LANG:                 en_US.UTF-8
OSTYPE:               darwin23.0
TERM:                 tmux-256color
TERM_PROGRAM:         tmux
TERM_PROGRAM_VERSION: 3.4
ZIM_HOME:             /Users/krikava/.zim
ZSH_VERSION:          5.9
```

**Comment by fikovnik** [comment]
Looks like it is cause by this change: https://github.com/zimfw/completion/compare/ef4d8a554ea8bb81e8fdb2d789289e8844d3a10f...0a1d9c7d2cc269da7ece160401e5e2cc3e6be243

**Comment by ericbn** [comment]
Hi @fikovnik. I've reverted the changes you mentioned in the completion module. It indeed fixes this issue. Thank you for digging into the root cause.
